CREATE TABLE `templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`genre` varchar(100) NOT NULL,
	`description` text,
	`coverColor` varchar(7) DEFAULT '#1a1a1a',
	`accentColor` varchar(7) DEFAULT '#ff6b6b',
	`bodyFont` varchar(100) DEFAULT 'Helvetica',
	`headingFont` varchar(100) DEFAULT 'Helvetica-Bold',
	`bodyFontSize` int DEFAULT 12,
	`headingFontSize` int DEFAULT 24,
	`lineHeight` varchar(10) DEFAULT '1.5',
	`marginTop` varchar(10) DEFAULT '0.75',
	`marginBottom` varchar(10) DEFAULT '0.75',
	`marginLeft` varchar(10) DEFAULT '0.75',
	`marginRight` varchar(10) DEFAULT '0.75',
	`chapterStyle` varchar(50) DEFAULT 'numbered',
	`includeTableOfContents` int DEFAULT 1,
	`includeFrontMatter` int DEFAULT 1,
	`includeBackMatter` int DEFAULT 1,
	`isPublic` int DEFAULT 1,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `templates_id` PRIMARY KEY(`id`)
);
